# Generated by Django 4.1.5 on 2023-01-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_dynamics_of_salary_graphic', models.ImageField(upload_to='')),
            ],
        ),
    ]
