# Generated by Django 4.1.5 on 2023-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_dynamics_of_salary_graphic', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='demand',
            name='year_dynamics_of_salary_graphic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
