# Generated by Django 4.1.5 on 2023-01-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0002_geo_alter_demand_year_dynamics_of_salary_graphic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geo',
            old_name='year_dynamics_of_salary_graphic',
            new_name='city_dynamics_of_salary_graphic',
        ),
    ]
