# Generated by Django 4.1.5 on 2023-01-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0003_rename_year_dynamics_of_salary_graphic_geo_city_dynamics_of_salary_graphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
