# Generated by Django 4.1.5 on 2023-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0004_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='index_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
