# Generated by Django 4.1.5 on 2023-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0005_index_index_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='table',
            field=models.FilePathField(default=1, verbose_name='C:\\Users\\Owner\\PycharmProjects\\pythonProject\\project\\dba\\analysis\\report_years.xlsx'),
            preserve_default=False,
        ),
    ]
