# Generated by Django 4.1.5 on 2023-01-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0007_alter_demand_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_graphic', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='demand',
            name='table',
        ),
    ]
